# Generated by Django 4.2 on 2023-04-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_alter_bid_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="listing",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
